import { Evidence } from '../types/evidence';

export class EvidenceRecorder {
  exportToJSON(timeline: Evidence[]): void {
    if (typeof window === 'undefined') return;

    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(timeline, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `evidence_fusion_log_${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  }

  exportToCSV(timeline: Evidence[]): void {
    if (typeof window === 'undefined') return;

    const headers = ['ID', 'Version', 'Timestamp', 'Type', 'Title', 'Description', 'Generated By', 'Confidence', 'Severity', 'Status', 'Duration (s)', 'Supporting Event IDs'];
    const rows = timeline.map((e) => [
      e.id,
      e.version,
      e.timestamp,
      e.type,
      `"${e.title.replace(/"/g, '""')}"`,
      `"${e.description.replace(/"/g, '""')}"`,
      e.generatedBy,
      e.confidence,
      e.severity,
      e.status,
      e.duration,
      `"${e.supportingEvents.join(',')}"`,
    ]);

    const csvContent = [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
    const dataStr = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvContent);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `evidence_fusion_log_${Date.now()}.csv`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  }
}

export const evidenceRecorder = new EvidenceRecorder();
export default evidenceRecorder;
